language: php

services: docker

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

env:
    - ABTEST=client
    - ABTEST=server

matrix:
    allow_failures:
        - php: nightly

before_install:
    - docker pull crossbario/autobahn-testsuite

before_script:
    - composer install
    - sh tests/ab/run_ab_tests.sh

script:
    - vendor/bin/phpunit
