language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
    - export PATH=$HOME/.local/bin:$PATH
    - pip install autobahntestsuite --user `whoami`
    - pip list autobahntestsuite --user `whoami`

before_script:
    - composer install
    - sh tests/ab/run_ab_tests.sh

script:
    - phpunit